### ISSUE TITLE
Manifest file not found by portal_client error

### ISSUE THREAD

**Issue by reedstubbendieck** [IGS/portal_client#3]
When I run the following command: `docker run -ti --rm portal_client portal_client -m example_manifest.tsv -d ./` I get the following error:

`Traceback (most recent call last):
  File "/usr/local/bin/portal_client", line 9, in <module>
    portal_client.main()
  File "/usr/local/lib/python3.6/dist-packages/portal_client.py", line 191, in main
    manifest = file_to_manifest(args.manifest)
  File "/usr/local/lib/python3.6/dist-packages/convert_to_manifest.py", line 22, in file_to_manifest
    with open(file) as tsv:
FileNotFoundError: [Errno 2] No such file or directory: 'example_manifest.tsv'`

**Comment by victor73** [comment]
Since portal_client is being run via docker, the execution is happening inside the container, and the example_manifest.tsv is not in the working directory in the container. If you wish to use the docker container with your own manifest files, you will probably need to map the directory that contains the manifest to the container using docker's volume support (-v) . Either that, or you must copy your manifest INTO the container before executing `docker run` with an absolute path to where you placed the file...

**Comment by victor73** [comment]
Did the above comment help resolve your issue?

**Comment by victor73** [comment]
Closing.
